/**
 * Multi-city registry for ChargePush.
 *
 * Design notes:
 * - Each city has a stable URL slug used by the /city/:slug landing pages and the
 *   city switcher. Slugs are the source of truth; never derive them from display names.
 * - `active` controls whether the city appears in switchers and nav. Launch city first.
 * - Spot data is already stored with a `city` field; filtering is client-side, so
 *   activation is purely a registry change until the network grows.
 */
export interface CityInfo {
  slug: string;
  name: string;
  state: string;
  tagline: string;
  lat: number;
  lng: number;
  active: boolean;
  launch: boolean;
  seo: { hero: string; sub: string; why: string; faqLead: string };
}

export const CITIES: CityInfo[] = [
  { slug: "kolhapur", name: "Kolhapur", state: "Maharashtra", tagline: "Launch city — charging access on every street", lat: 16.705, lng: 74.2433, active: true, launch: true, seo: { hero: "EV Charging Access in Kolhapur", sub: "Verified charging points across Kolhapur's neighborhoods — from Rankala to Shahupuri.", why: "Kolhapur's two-wheeler riders need everyday charging access within walking distance. ChargePush hosts list their charging access so riders keep moving without detours.", faqLead: "Find EV charging near me in Kolhapur" } },
  { slug: "pune", name: "Pune", state: "Maharashtra", tagline: "Coming soon", lat: 18.5204, lng: 73.8567, active: false, launch: false, seo: { hero: "EV Charging Access in Pune", sub: "Neighborhood charging across Pune — Kothrud to Viman Nagar.", why: "Pune's fast-growing EV fleet deserves charging closer than distant parking lots. ChargePush turns verified home outlets into a citywide network.", faqLead: "Find EV charging near me in Pune" } },
  { slug: "mumbai", name: "Mumbai", state: "Maharashtra", tagline: "Coming soon", lat: 19.076, lng: 72.8777, active: false, launch: false, seo: { hero: "EV Charging Access in Mumbai", sub: "Charging points within walking distance across Mumbai's suburbs.", why: "In Mumbai, every kilometer of commute counts. ChargePush riders top up at verified outlets near home, work, or college.", faqLead: "Find EV charging near me in Mumbai" } },
  { slug: "nagpur", name: "Nagpur", state: "Maharashtra", tagline: "Coming soon", lat: 21.1458, lng: 79.0882, active: false, launch: false, seo: { hero: "EV Charging Spots in Nagpur", sub: "Home charging network spreading through Nagpur's neighborhoods.", why: "Nagpur rides electric early — ChargePush hosts make everyday top-ups a matter of minutes, not detours.", faqLead: "Find EV charging near me in Nagpur" } },
  { slug: "bangalore", name: "Bangalore", state: "Karnataka", tagline: "Coming soon", lat: 12.9716, lng: 77.5946, active: false, launch: false, seo: { hero: "EV Charging Spots in Bangalore", sub: "Charging near you in Indiranagar, Koramangala, Jayanagar and beyond.", why: "Bangalore's delivery riders and commuters charge daily. ChargePush puts verified outlets on their doorstep instead of across the city.", faqLead: "Find EV charging near me in Bangalore" } },
  { slug: "hyderabad", name: "Hyderabad", state: "Telangana", tagline: "Coming soon", lat: 17.385, lng: 78.4867, active: false, launch: false, seo: { hero: "EV Charging Spots in Hyderabad", sub: "Neighborhood charging across Secunderabad, HITEC City, and the old city.", why: "Hyderabad's two-wheeler economy is electric-first. ChargePush hosts earn passive income while riders skip long queues.", faqLead: "Find EV charging near me in Hyderabad" } },
  { slug: "chennai", name: "Chennai", state: "Tamil Nadu", tagline: "Coming soon", lat: 13.0827, lng: 80.2707, active: false, launch: false, seo: { hero: "EV Charging Spots in Chennai", sub: "Charging points near T. Nagar, Adyar, Anna Nagar and every neighborhood in between.", why: "Chennai heat makes waiting painful — ChargePush riders charge at home outlets minutes away, not across town.", faqLead: "Find EV charging near me in Chennai" } },
  { slug: "delhi", name: "Delhi NCR", state: "Delhi", tagline: "Coming soon", lat: 28.7041, lng: 77.1025, active: false, launch: false, seo: { hero: "EV Charging Spots in Delhi NCR", sub: "A plug in every colony — from Dwarka to Noida and Gurugram.", why: "Delhi's two-wheeler adoption is among India's fastest. ChargePush brings verified charging to each colony's doorstep.", faqLead: "Find EV charging near me in Delhi NCR" } },
  { slug: "ahmedabad", name: "Ahmedabad", state: "Gujarat", tagline: "Coming soon", lat: 23.0225, lng: 72.5714, active: false, launch: false, seo: { hero: "EV Charging Spots in Ahmedabad", sub: "Home charging across Maninagar, Bopal, Satellite and more.", why: "Ahmedabad's riders deserve charging that fits their day. ChargePush hosts open their outlets across the city.", faqLead: "Find EV charging near me in Ahmedabad" } },
  { slug: "jaipur", name: "Jaipur", state: "Rajasthan", tagline: "Coming soon", lat: 26.9124, lng: 75.7873, active: false, launch: false, seo: { hero: "EV Charging Spots in Jaipur", sub: "Neighborhood charging from Vaishali Nagar to Malviya Nagar.", why: "Jaipur's EV two-wheelers are multiplying — ChargePush keeps the network growing with verified home outlets.", faqLead: "Find EV charging near me in Jaipur" } },
  { slug: "lucknow", name: "Lucknow", state: "Uttar Pradesh", tagline: "Coming soon", lat: 26.8467, lng: 80.9462, active: false, launch: false, seo: { hero: "EV Charging Spots in Lucknow", sub: "Charging near Gomti Nagar, Aliganj, and Indira Nagar.", why: "Lucknow riders can now charge without crossing the city. ChargePush hosts bring the plug to the neighborhood.", faqLead: "Find EV charging near me in Lucknow" } },
  { slug: "kolkata", name: "Kolkata", state: "West Bengal", tagline: "Coming soon", lat: 22.5726, lng: 88.3639, active: false, launch: false, seo: { hero: "EV Charging Spots in Kolkata", sub: "Home charging points across Howrah, Salt Lake, Garia and beyond.", why: "Kolkata's iconic two-wheeler culture goes electric with ChargePush — a verified outlet in every para.", faqLead: "Find EV charging near me in Kolkata" } },
  { slug: "bhopal", name: "Bhopal", state: "Madhya Pradesh", tagline: "Coming soon", lat: 23.2599, lng: 77.4126, active: false, launch: false, seo: { hero: "EV Charging Spots in Bhopal", sub: "Neighborhood charging across MP Nagar, Kolar Road and the old city.", why: "Bhopal's riders charge at home outlets minutes from where they live and work.", faqLead: "Find EV charging near me in Bhopal" } },
  { slug: "indore", name: "Indore", state: "Madhya Pradesh", tagline: "Coming soon", lat: 22.7196, lng: 75.8577, active: false, launch: false, seo: { hero: "EV Charging Spots in Indore", sub: "Charging near Vijay Nagar, Palasia and Rau.", why: "Indore's clean-city spirit extends to electric mobility — ChargePush hosts power the next generation of riders.", faqLead: "Find EV charging near me in Indore" } },
  { slug: "nashik", name: "Nashik", state: "Maharashtra", tagline: "Coming soon", lat: 19.9975, lng: 73.7898, active: false, launch: false, seo: { hero: "EV Charging Spots in Nashik", sub: "Home charging across College Road, Gangapur Road and more.", why: "Nashik riders get everyday charging without detours — verified outlets in their own lanes.", faqLead: "Find EV charging near me in Nashik" } },
  { slug: "vadodara", name: "Vadodara", state: "Gujarat", tagline: "Coming soon", lat: 22.3072, lng: 73.1812, active: false, launch: false, seo: { hero: "EV Charging Spots in Vadodara", sub: "Neighborhood charging in Alkapuri, Manjalpur and Karelibaug.", why: "Vadodara's two-wheeler riders top up at verified home outlets across the city.", faqLead: "Find EV charging near me in Vadodara" } },
  { slug: "surat", name: "Surat", state: "Gujarat", tagline: "Coming soon", lat: 21.1702, lng: 72.8311, active: false, launch: false, seo: { hero: "EV Charging Spots in Surat", sub: "Charging points across Vesu, Adajan, and the old city.", why: "Surat's busy riders charge near their shops and homes — ChargePush hosts make it happen.", faqLead: "Find EV charging near me in Surat" } },
  { slug: "coimbatore", name: "Coimbatore", state: "Tamil Nadu", tagline: "Coming soon", lat: 11.0168, lng: 76.9558, active: false, launch: false, seo: { hero: "EV Charging Spots in Coimbatore", sub: "Home charging across RS Puram, Peelamedu and Gandhipuram.", why: "Coimbatore's EV adoption rides on neighborhood trust — exactly what ChargePush hosts deliver.", faqLead: "Find EV charging near me in Coimbatore" } },
  { slug: "kochi", name: "Kochi", state: "Kerala", tagline: "Coming soon", lat: 9.9312, lng: 76.2673, active: false, launch: false, seo: { hero: "EV Charging Spots in Kochi", sub: "Charging near Kakkanad, Edappally, Fort Kochi and Ernakulam.", why: "Kerala's electric two-wheelers need charging that matches their pace — ChargePush hosts deliver.", faqLead: "Find EV charging near me in Kochi" } },
  { slug: "thiruvananthapuram", name: "Thiruvananthapuram", state: "Kerala", tagline: "Coming soon", lat: 8.5241, lng: 76.9366, active: false, launch: false, seo: { hero: "EV Charging Spots in Thiruvananthapuram", sub: "Neighborhood charging across Kazhakootam, Kowdiar and Ulloor.", why: "Capital-city commuters charge at verified home outlets minutes from office.", faqLead: "Find EV charging near me in Thiruvananthapuram" } },
  { slug: "visakhapatnam", name: "Visakhapatnam", state: "Andhra Pradesh", tagline: "Coming soon", lat: 17.6868, lng: 83.2185, active: false, launch: false, seo: { hero: "EV Charging Spots in Visakhapatnam", sub: "Home charging across Gajuwaka, MVP Colony and Daba Gardens.", why: "Vizag riders skip long detours — ChargePush hosts bring charging to the neighborhood.", faqLead: "Find EV charging near me in Visakhapatnam" } },
  { slug: "vijayawada", name: "Vijayawada", state: "Andhra Pradesh", tagline: "Coming soon", lat: 16.5062, lng: 80.648, active: false, launch: false, seo: { hero: "EV Charging Spots in Vijayawada", sub: "Charging near Benz Circle, Gunadala and Patamata.", why: "Vijayawada's two-wheeler riders charge at verified home outlets across the city.", faqLead: "Find EV charging near me in Vijayawada" } },
  { slug: "mysore", name: "Mysuru", state: "Karnataka", tagline: "Coming soon", lat: 12.2958, lng: 76.6394, active: false, launch: false, seo: { hero: "EV Charging Spots in Mysuru", sub: "Neighborhood charging in Jayalakshmipuram, Vijayanagar and more.", why: "Mysuru's heritage-city pace meets modern charging — a plug in every neighborhood.", faqLead: "Find EV charging near me in Mysuru" } },
  { slug: "chandigarh", name: "Chandigarh", state: "Chandigarh", tagline: "Coming soon", lat: 30.7333, lng: 76.7794, active: false, launch: false, seo: { hero: "EV Charging Spots in Chandigarh", sub: "Charging across the sectors — 22 to 45 and beyond.", why: "Planned-city riders enjoy planned charging: verified home outlets in every sector.", faqLead: "Find EV charging near me in Chandigarh" } },
  { slug: "ludhiana", name: "Ludhiana", state: "Punjab", tagline: "Coming soon", lat: 30.901, lng: 75.8573, active: false, launch: false, seo: { hero: "EV Charging Spots in Ludhiana", sub: "Home charging across Model Town, Civil Lines and Dugri.", why: "Ludhiana's two-wheeler heartland charges at verified home outlets nearby.", faqLead: "Find EV charging near me in Ludhiana" } },
  { slug: "amritsar", name: "Amritsar", state: "Punjab", tagline: "Coming soon", lat: 31.634, lng: 74.8723, active: false, launch: false, seo: { hero: "EV Charging Spots in Amritsar", sub: "Charging near Ranjit Avenue, Hall Bazaar and Lawrence Road.", why: "Amritsar riders charge near the Golden City's neighborhoods via ChargePush hosts.", faqLead: "Find EV charging near me in Amritsar" } },
  { slug: "agra", name: "Agra", state: "Uttar Pradesh", tagline: "Coming soon", lat: 27.1767, lng: 78.0081, active: false, launch: false, seo: { hero: "EV Charging Spots in Agra", sub: "Neighborhood charging in Tajganj, Kamla Nagar and Khandari.", why: "Agra's electric two-wheelers find charging within walking distance — thanks to local hosts.", faqLead: "Find EV charging near me in Agra" } },
  { slug: "varanasi", name: "Varanasi", state: "Uttar Pradesh", tagline: "Coming soon", lat: 25.3176, lng: 82.9739, active: false, launch: false, seo: { hero: "EV Charging Spots in Varanasi", sub: "Home charging across Sigra, Lanka and Bhelupur.", why: "Ancient lanes, modern charging: ChargePush hosts power Varanasi's electric riders.", faqLead: "Find EV charging near me in Varanasi" } },
  { slug: "patna", name: "Patna", state: "Bihar", tagline: "Coming soon", lat: 25.6093, lng: 85.1376, active: false, launch: false, seo: { hero: "EV Charging Spots in Patna", sub: "Charging near Kankarbagh, Boring Road and Rajendra Nagar.", why: "Patna's growing EV fleet charges at verified home outlets across the city.", faqLead: "Find EV charging near me in Patna" } },
  { slug: "guwahati", name: "Guwahati", state: "Assam", tagline: "Coming soon", lat: 26.1445, lng: 91.7362, active: false, launch: false, seo: { hero: "EV Charging Spots in Guwahati", sub: "Neighborhood charging in GS Road, Ulubari and Dispur.", why: "Guwahati riders charge at home outlets minutes from home and office.", faqLead: "Find EV charging near me in Guwahati" } },
  { slug: "bhubaneswar", name: "Bhubaneswar", state: "Odisha", tagline: "Coming soon", lat: 20.2961, lng: 85.8245, active: false, launch: false, seo: { hero: "EV Charging Spots in Bhubaneswar", sub: "Charging across Patia, Nayapalli and Saheed Nagar.", why: "Odisha's smart-city capital charges with ChargePush hosts in every neighborhood.", faqLead: "Find EV charging near me in Bhubaneswar" } },
  { slug: "raipur", name: "Raipur", state: "Chhattisgarh", tagline: "Coming soon", lat: 21.2514, lng: 81.6296, active: false, launch: false, seo: { hero: "EV Charging Spots in Raipur", sub: "Home charging in Civil Lines, Shankar Nagar and Tatibandh.", why: "Raipur's two-wheeler riders top up at verified outlets nearby.", faqLead: "Find EV charging near me in Raipur" } },
  { slug: "ranchi", name: "Ranchi", state: "Jharkhand", tagline: "Coming soon", lat: 23.3441, lng: 85.3096, active: false, launch: false, seo: { hero: "EV Charging Spots in Ranchi", sub: "Neighborhood charging across Doranda, Lalpur and Harmu.", why: "Ranchi riders charge at home outlets close to the heart of the city.", faqLead: "Find EV charging near me in Ranchi" } },
  { slug: "dehradun", name: "Dehradun", state: "Uttarakhand", tagline: "Coming soon", lat: 30.3165, lng: 78.0322, active: false, launch: false, seo: { hero: "EV Charging Spots in Dehradun", sub: "Charging near Rajpur Road, Vasant Vihar and Clement Town.", why: "Hill-city commuters charge at verified home outlets across Dehradun.", faqLead: "Find EV charging near me in Dehradun" } },
  { slug: "kanpur", name: "Kanpur", state: "Uttar Pradesh", tagline: "Coming soon", lat: 26.4499, lng: 80.3319, active: false, launch: false, seo: { hero: "EV Charging Spots in Kanpur", sub: "Home charging in Swaroop Nagar, Kakadeo and The Mall Road.", why: "Kanpur's riders find charging within walking distance through local hosts.", faqLead: "Find EV charging near me in Kanpur" } },
  { slug: "meerut", name: "Meerut", state: "Uttar Pradesh", tagline: "Coming soon", lat: 28.9845, lng: 77.7064, active: false, launch: false, seo: { hero: "EV Charging Spots in Meerut", sub: "Neighborhood charging across Shastri Nagar, Begum Bridge and more.", why: "Meerut's electric two-wheelers charge at verified home outlets nearby.", faqLead: "Find EV charging near me in Meerut" } },
  { slug: "aurangabad", name: "Aurangabad", state: "Maharashtra", tagline: "Coming soon", lat: 19.8762, lng: 75.3433, active: false, launch: false, seo: { hero: "EV Charging Spots in Aurangabad", sub: "Charging near Cidco, Jawahar Nagar and Station Road.", why: "Aurangabad riders charge close to home with ChargePush's verified host network.", faqLead: "Find EV charging near me in Aurangabad" } },
  { slug: "solapur", name: "Solapur", state: "Maharashtra", tagline: "Coming soon", lat: 17.6599, lng: 75.9064, active: false, launch: false, seo: { hero: "EV Charging Spots in Solapur", sub: "Home charging across Jule Solapur, Akkalkot Road and more.", why: "Solapur's riders top up at verified home outlets across the city.", faqLead: "Find EV charging near me in Solapur" } },
  { slug: "hubli", name: "Hubli-Dharwad", state: "Karnataka", tagline: "Coming soon", lat: 15.3647, lng: 75.124, active: false, launch: false, seo: { hero: "EV Charging Spots in Hubli-Dharwad", sub: "Neighborhood charging in Vidyanagar, Keshwapur and beyond.", why: "Twin-city riders charge at verified home outlets minutes away.", faqLead: "Find EV charging near me in Hubli-Dharwad" } },
  { slug: "mangalore", name: "Mangaluru", state: "Karnataka", tagline: "Coming soon", lat: 12.9141, lng: 74.856, active: false, launch: false, seo: { hero: "EV Charging Spots in Mangaluru", sub: "Charging near Bejai, Pandeshwar and Kadri.", why: "Coastal-city riders charge at verified home outlets across Mangaluru.", faqLead: "Find EV charging near me in Mangaluru" } },
  { slug: "madurai", name: "Madurai", state: "Tamil Nadu", tagline: "Coming soon", lat: 9.9252, lng: 78.1198, active: false, launch: false, seo: { hero: "EV Charging Spots in Madurai", sub: "Home charging in Anna Nagar, KK Nagar and T. Nagar roads.", why: "Temple-city riders find charging within walking distance via ChargePush hosts.", faqLead: "Find EV charging near me in Madurai" } },
  { slug: "tiruchirappalli", name: "Tiruchirappalli", state: "Tamil Nadu", tagline: "Coming soon", lat: 10.7905, lng: 78.6927, active: false, launch: false, seo: { hero: "EV Charging Spots in Tiruchirappalli", sub: "Neighborhood charging across Srirangam, cantonment and beyond.", why: "Trichy's riders charge at verified home outlets close to the Kaveri banks.", faqLead: "Find EV charging near me in Tiruchirappalli" } },
  { slug: "noida", name: "Noida", state: "Uttar Pradesh", tagline: "Coming soon", lat: 28.5355, lng: 77.391, active: false, launch: false, seo: { hero: "EV Charging Spots in Noida", sub: "Charging across Sectors 18, 62, 150 and every society in between.", why: "Noida's delivery and office riders charge within their sectors via ChargePush hosts.", faqLead: "Find EV charging near me in Noida" } },
  { slug: "gurugram", name: "Gurugram", state: "Haryana", tagline: "Coming soon", lat: 28.4595, lng: 77.0266, active: false, launch: false, seo: { hero: "EV Charging Spots in Gurugram", sub: "Neighborhood charging from Cyber Hub to Sohna Road.", why: "Millennium-city riders skip long queues — a verified outlet in every sector.", faqLead: "Find EV charging near me in Gurugram" } },
  { slug: "faridabad", name: "Faridabad", state: "Haryana", tagline: "Coming soon", lat: 28.4089, lng: 77.3178, active: false, launch: false, seo: { hero: "EV Charging Spots in Faridabad", sub: "Home charging in Sectors 15, 16, 21 and the old city.", why: "Faridabad's two-wheeler riders charge at verified home outlets nearby.", faqLead: "Find EV charging near me in Faridabad" } },
  { slug: "ghaziabad", name: "Ghaziabad", state: "Uttar Pradesh", tagline: "Coming soon", lat: 28.6692, lng: 77.4538, active: false, launch: false, seo: { hero: "EV Charging Spots in Ghaziabad", sub: "Charging across Raj Nagar, Indirapuram and Vaishali.", why: "Ghaziabad commuters charge at home outlets minutes from their metro stop.", faqLead: "Find EV charging near me in Ghaziabad" } },
  { slug: "mathura", name: "Mathura", state: "Uttar Pradesh", tagline: "Coming soon", lat: 27.4924, lng: 77.6737, active: false, launch: false, seo: { hero: "EV Charging Spots in Mathura", sub: "Neighborhood charging near Krishna Janmabhoomi and the ghats.", why: "Pilgrim-city riders charge at verified home outlets across Mathura.", faqLead: "Find EV charging near me in Mathura" } },
  { slug: "tirupati", name: "Tirupati", state: "Andhra Pradesh", tagline: "Coming soon", lat: 13.6288, lng: 79.4192, active: false, launch: false, seo: { hero: "EV Charging Spots in Tirupati", sub: "Charging near the temple city's neighborhoods and bus stand.", why: "Tirupati's riders charge at verified home outlets before the climb.", faqLead: "Find EV charging near me in Tirupati" } },
  { slug: "salem", name: "Salem", state: "Tamil Nadu", tagline: "Coming soon", lat: 11.6643, lng: 78.146, active: false, launch: false, seo: { hero: "EV Charging Spots in Salem", sub: "Home charging across Junction Main Road, Fairlands and more.", why: "Salem's riders top up at verified home outlets across the city.", faqLead: "Find EV charging near me in Salem" } },
  { slug: "belgaum", name: "Belagavi", state: "Karnataka", tagline: "Coming soon", lat: 15.8497, lng: 74.4977, active: false, launch: false, seo: { hero: "EV Charging Spots in Belagavi", sub: "Neighborhood charging in Tilakwadi, Camp and Shahapur.", why: "Belagavi's electric riders charge at verified home outlets nearby.", faqLead: "Find EV charging near me in Belagavi" } },
  { slug: "gwalior", name: "Gwalior", state: "Madhya Pradesh", tagline: "Coming soon", lat: 26.2183, lng: 78.1828, active: false, launch: false, seo: { hero: "EV Charging Spots in Gwalior", sub: "Charging near Lashkar, Morar and the city center.", why: "Fort-city riders charge at home outlets minutes from where they live.", faqLead: "Find EV charging near me in Gwalior" } },
  { slug: "jabalpur", name: "Jabalpur", state: "Madhya Pradesh", tagline: "Coming soon", lat: 23.1815, lng: 79.9864, active: false, launch: false, seo: { hero: "EV Charging Spots in Jabalpur", sub: "Home charging across Napier Town, Wright Town and Ranjhi.", why: "Jabalpur riders charge at verified home outlets across the marble city.", faqLead: "Find EV charging near me in Jabalpur" } },
];

export function getCityBySlug(slug: string): CityInfo | undefined {
  return CITIES.find((c) => c.slug === slug);
}

export function getActiveCities(): CityInfo[] {
  return CITIES.filter((c) => c.active);
}

export function getLaunchCity(): CityInfo {
  return CITIES.find((c) => c.launch) ?? CITIES[0];
}

/**
 * Normalize a spot's stored city (case/whitespace tolerant) to a registry slug.
 */
export function spotCitySlug(city: string | undefined): string | null {
  if (!city) return null;
  const norm = city.trim().toLowerCase();
  const match = CITIES.find(
    (c) => c.name.toLowerCase() === norm || c.slug.toLowerCase() === norm
  );
  return match ? match.slug : null;
}

/** Filter spots to a city slug; returns all spots when slug is null. */
export function filterSpotsByCity<T extends { city?: string }>(
  spots: T[],
  slug: string | null
): T[] {
  if (!slug) return spots;
  return spots.filter((s) => spotCitySlug(s.city) === slug);
}
